---
version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ${PATH_CONFIG}/homepage:/app/config
      - ${PATH_DATA}/homepage/images:/app/public/images
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`home.${DEFAULT_DOMAIN}`)"
      - "traefik.http.routers.homepage.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - proxy
      - docker-proxy

networks:
  proxy:
    external: true
  docker-proxy:
    external: true

